add_newline = true

format = """
$hostname\
$directory\
$c\
${custom.cpp}\
$nodejs\
$golang\
$rust\
$lua\
$python\
$java\
$fill\
$username\
$git_branch\
$git_status\
$line_break\
$character
"""

[username]
format = '[](fg:bright-cyan)[$user]($style)[](fg:bright-cyan)'
style_user = 'bold italic fg:black bg:bright-cyan'
disabled = false
show_always = true

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
vimcmd_symbol = '[](bold green) '

[fill]
symbol = ' '

[package]
disabled = true

[directory]
format = '[](fg:yellow)[$path]($style)[](fg:yellow)[$read_only](bold fg:red) '
style = 'bold fg:black bg:yellow'
read_only = '  '

[git_branch]
always_show_remote = true
format = ' [](fg:bright-purple)[ $symbol $branch ]($style)[](fg:bright-purple)'
style = 'bold bg:bright-purple fg:black'
symbol = ''

[git_status]
format = '([$conflicted$staged$untracked$modified]($style))'
staged = '[  ](green)'
untracked = '[  ](red)'
modified = '[  ](yellow)'
conflicted = '[ ](cyan)'

[nodejs]
format = '[$symbol](fg:bright-yellow)'
symbol = '  /󰎙 '
detect_folders = ['node_modules']
detect_files = ['tsconfig.json','package.json']

[golang]
format = '[$symbol](fg:bright-blue)'
detect_files = ['go.mod','go.sum']
detect_extensions = ['go']
symbol = '  '

[rust]
format = '[$symbol](fg:bright-red)'
detect_files = ['.rs']
symbol = ' 󱘗 '

[lua]
format = '[$symbol](fg:bright-green)'
symbol = ' 󰢱 '

[python]
format = '[$symbol$virtualenv](fg:blue)'
symbol = ' 󰌠 '

[custom.cpp]
format = '[$symbol](fg:bright-blue)'
detect_extensions = ['cpp']
symbol = "   "
style = 'bold fg:navy'

[java]
format = '[$symbol](fg:red)'
symbol = '  '
