# Detach window to a new tab
map ctrl+f3 detach_window new-tab

# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map alt+shift+h launch --location=hsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side
map alt+shift+v launch --location=vsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side if the existing window is wide or
# one above the other if the existing window is tall.
map ctrl+alt+s launch --location=split

# Move the active window in the indicated direction
map ctrl+shift+k move_window up
map ctrl+shift+h move_window left
map ctrl+shift+l move_window right
map ctrl+shift+j move_window down

# Switch focus to the neighboring window in the indicated direction
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down
